### ISSUE TITLE
Proposal: 支持sidecar自动injection的部署方式

### ISSUE THREAD

**Issue by chaunceyjiang** [loggie-io/loggie-operator#3]
## 总体思路
目前`loggie-operator`支持`deployment`和`daemonSet` 两种方式来部署loggie,但是在某些受限场景下只能选择使用Sidecar的方式采集容器日志
https://loggie-io.github.io/docs/user-guide/use-in-kubernetes/sidecar/
## 实现细节
目前`loggie-operator` 有两个`CRD Controller`,分别是`LogCluster controller`,`LogConfig controller`

### LogConfig Controller
它的主要作用是watch `LogConfig`,然后转换为CM,挂载到容器中,供`loggie`读取使用

###  LogCluster Controller
它的主要作用是watch `LogCluster` ,然后根据其中的配置,来部署`loggie`
因此,需要在`LogClusterSpec.Type` 中增加一个`SideCar`类型 ,同时增加[部署判断逻辑](https://github.com/loggie-io/loggie-operator/blob/cb449387390e6e39b91340737058a91cbfb0c14b/pkg/controllers/logcluster/logcluster_controller.go#L70-L74)
```
if lc.Spec.Type == v1beta1.SideCar {
   return ctrl.Result{}, nil  //因为我们会采用sidecar 注入到业务pod中的方式,因此这里不做任何处理
}
```
### SideCar 注入
sidecar 注入通用方法是通过 `admission`中的` MutatingWebhook` 来修改拦截业务`Pod`的创建,然后向其中`containers`中增加
`agent`
在本项目中 通过[mgr](https://github.com/loggie-io/loggie-operator/blob/cb449387390e6e39b91340737058a91cbfb0c14b/cmd/operator/main.go#L68)获取到webhookserver.然后注册wehhook handler .
```
	hookServer := mgr.GetWebhookServer()
	hookServer.Register("/loggie-pod-inject-sidecar", &webhook.Admission{
		Handler: &PodInject{
			Client:  mgr.GetClient(),
		},
	})



type PodInject struct {
	client.Client
	decoder *admission.Decoder
}

func (r *PodInject) InjectDecoder(d *admission.Decoder) error {
	r.decoder = d
	return nil
}

func (r *PodInject) Handle(ctx context.Context, req admission.Request) admission.Response {
	// watch pod
	pod := &corev1.Pod{}
	if err := r.decoder.Decode(req, pod); err != nil {
		return admission.Errored(http.StatusBadRequest, err)
	}
	// inject loggie container 
        // TODO
        ...

        // 目前不建议在配置文件中enable kubernetes discovery，由于打开后会请求Kubernetes，在Pods比较多的时候，会 Kubernetes造成一定压力，所以无法使用LogConfig CRD，需要使用configMap挂载配置文件。
        // 由于不使用Kubernetes discovery，这里的fields并不会被自动加上Pod的元信息，需要使用fieldsFromEnv的方式从Pod的环境变量里获取
	...

	// marshal pod
	marshaledPod, err := json.Marshal(pod)
	if err != nil {
		return admission.Errored(http.StatusInternalServerError, err)
	}
	return admission.PatchResponseFromRaw(req.Object.Raw, marshaledPod)
}

```

#### MutatingWebhookConfiguration 
在`operator` 中注册webhook hander后,需要增加对应的rbac和admission配置
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: loggie-operator-admission
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        namespace: loggie-operator-system
        name: loggie-operator-admission
        path: /oggie-pod-inject-sidecar
    failurePolicy: Fail
    name: mutating.pod.operator.loggie.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods

    sideEffects: NoneOnDryRun
```

#### RBAC
因为在webhook 中需要watch pod,因此需要在`loggie-operator `的`RBAC`中增加对`Pod`的权限

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
```
